// flow-typed signature: 4b28a9b0245b32c77bd3d6aab1ce1380
// flow-typed version: <<STUB>>/babel-plugin-transform-proto-to-assign_v^6.26.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-proto-to-assign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-proto-to-assign' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-proto-to-assign/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-proto-to-assign/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-proto-to-assign/lib/index'>;
}
