// flow-typed signature: d1c04c33c850c82b42e769a141939802
// flow-typed version: <<STUB>>/webpack-serve_v^0.2.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-serve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-serve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-serve/cli' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/bus' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/config' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/global' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/options' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/server' {
  declare module.exports: any;
}

declare module 'webpack-serve/lib/WebpackServeError' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-serve/cli.js' {
  declare module.exports: $Exports<'webpack-serve/cli'>;
}
declare module 'webpack-serve/index' {
  declare module.exports: $Exports<'webpack-serve'>;
}
declare module 'webpack-serve/index.js' {
  declare module.exports: $Exports<'webpack-serve'>;
}
declare module 'webpack-serve/lib/bus.js' {
  declare module.exports: $Exports<'webpack-serve/lib/bus'>;
}
declare module 'webpack-serve/lib/config.js' {
  declare module.exports: $Exports<'webpack-serve/lib/config'>;
}
declare module 'webpack-serve/lib/global.js' {
  declare module.exports: $Exports<'webpack-serve/lib/global'>;
}
declare module 'webpack-serve/lib/options.js' {
  declare module.exports: $Exports<'webpack-serve/lib/options'>;
}
declare module 'webpack-serve/lib/server.js' {
  declare module.exports: $Exports<'webpack-serve/lib/server'>;
}
declare module 'webpack-serve/lib/WebpackServeError.js' {
  declare module.exports: $Exports<'webpack-serve/lib/WebpackServeError'>;
}
